  <!-- Bootstrap JS dependencies -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>


<h4><center>Characters in the screenplay, and their arcs:</center></h4>
<fieldset class='border p-2'>
   <legend class='w-auto'><b>Yorkie</b></legend>
   <div class='your-div'>Yorkie is a shy and socially awkward woman who is searching for her true self and connection with others. Despite her reserved nature, she has a sweet and endearing personality. She is drawn to the world of San Junipero and is willing to take risks to find love and happiness.<br/><br/><b>Character Arc:</b>Yorkie goes through a transformation throughout the movie as she begins to open up and explore her desires. Initially, she is hesitant to step out of her comfort zone due to her restrictive upbringing and engagement to Greg. However, as she spends time with Kelly, she begins to reveal her inner turmoil and insecurities. Yorkie&#039;s character arc reaches its peak when she decides to take a risk and pursue a relationship with Kelly, despite the challenges in front of her. She ultimately finds love and happiness in San Junipero and faces her own impending death with bravery and honesty.<br/><br/><b>Character Arc Critique:</b>The character arc of Yorkie is well-developed and emotionally satisfying. However, some of the scenes in the movie feel repetitive and drag on the pacing. The audience can begin to anticipate the direction of the story and might become bored with the repetition.<br/><br/><b>Suggestions:</b>The character arc of Yorkie is well-developed and emotionally satisfying. However, some of the scenes in the movie feel repetitive and drag on the pacing. The audience can begin to anticipate the direction of the story and might become bored with the repetition.     </div>
</fieldset><fieldset class='border p-2'>
   <legend class='w-auto'><b>Kelly</b></legend>
   <div class='your-div'>Kelly is a confident, charismatic, and quirky woman who is comfortable with her sexuality and willing to take risks. She has had personal issues and insecurities in the past, which have made her cautious in relationships. Kelly is nurturing and empathetic, offering comfort and support to those around her. She has a mysterious past and is searching for her own identity in this simulated reality. As the story progresses, Kelly tries to come to terms with the morality of San Junipero, struggles with her past, and ultimately finds inner peace and acceptance in the afterlife.<br/><br/><b>Character Arc:</b>Kelly starts off as an adventurous and quirky woman who is interested in Yorkie. She is confident and charming, but also deals with her own personal issues and insecurities, leading her to not want attachments. As the story progresses, Kelly tries to find her own identity and struggles with the morality of the afterlife. She develops a deep love for Yorkie and is willing to do anything for her, leading her to ultimately upload herself. In the end, Kelly finds inner peace and acceptance by embracing the afterlife.<br/><br/><b>Character Arc Critique:</b>The character arc is well-developed and highlights the different aspects of Kelly&#039;s personality. However, the transition from being cautious in relationships to being willing to do anything for Yorkie seems abrupt and could have been better foreshadowed. Additionally, some parts of Kelly&#039;s backstory could have been fleshed out more to create a deeper connection with the audience. <br/><br/><b>Suggestions:</b>The character arc is well-developed and highlights the different aspects of Kelly&#039;s personality. However, the transition from being cautious in relationships to being willing to do anything for Yorkie seems abrupt and could have been better foreshadowed. Additionally, some parts of Kelly&#039;s backstory could have been fleshed out more to create a deeper connection with the audience.      </div>
</fieldset>
